name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ec2-3-26-184-242.ap-southeast-2.compute.amazonaws.com
        REMOTE_USER: ubuntu
        TARGET: /home/ubuntu/glucozbeat

      # with:
      #   args: "npm install && npm run build && pm2 restart all"
      # run: |
      #   mkdir -p ~/.ssh
      #   echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #   chmod 600 ~/.ssh/id_rsa
      #   ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
      #   scp -r * $REMOTE_USER@$REMOTE_HOST:$TARGET
      #   ssh $REMOTE_USER@$REMOTE_HOST "cd $TARGET && npm install && npm run build && pm2 restart all"
    - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: $REMOTE_HOST
          username: $REMOTE_USER
          key: $SSH_PRIVATE_KEY
          script: |
            cd $TARGET
            npm install
            npm run build
            pm2 restart all
